apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
spec:
  containers:
    - name: secret-container-devops
      image: debian:latest
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: blog-secret
          mountPath: /opt/games
  volumes:
    - name: blog-secret
      secret:
        secretName: blog
